"""schema update

Revision ID: 6ffa3faccf6a
Revises: 
Create Date: 2026-03-22 18:40:41.578825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ffa3faccf6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_brand_user_id'), table_name='brand')
    op.create_index(op.f('ix_brand_creator_id'), 'brand', ['creator_id'], unique=False)
    op.drop_column('brand', 'user_id')
    op.add_column('brand_tone', sa.Column('target_audience', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('brand_tone', sa.Column('brand_attributes', postgresql.ARRAY(sa.TEXT()), nullable=True))
    op.add_column('brand_tone', sa.Column('forbidden_words', postgresql.ARRAY(sa.TEXT()), nullable=True))
    op.add_column('brand_tone', sa.Column('system_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('brand_tone', sa.Column('brand_primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('brand_tone', sa.Column('aesthetics', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('brand_tone', sa.Column('music_pacing', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_tone', 'music_pacing')
    op.drop_column('brand_tone', 'aesthetics')
    op.drop_column('brand_tone', 'brand_primary_color')
    op.drop_column('brand_tone', 'system_instructions')
    op.drop_column('brand_tone', 'forbidden_words')
    op.drop_column('brand_tone', 'brand_attributes')
    op.drop_column('brand_tone', 'target_audience')
    op.add_column('brand', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_brand_creator_id'), table_name='brand')
    op.create_index(op.f('ix_brand_user_id'), 'brand', ['user_id'], unique=False)
    op.drop_column('brand', 'creator_id')
    # ### end Alembic commands ###
