name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: marketmint-489521
  REGION: africa-south1
  SERVICE_NAME: marketmint-service
  REPOSITORY: marketmint-repo
  # Use the 12-digit Project Number here
  WIF_PROVIDER: 'projects/114526386828/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  # Updated to use your service account name
  WIF_SERVICE_ACCOUNT: 'marketmint-service@marketmint-489521.iam.gserviceaccount.com'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}

      # 2. Configure Docker to use Artifact Registry
      - name: 'Docker Auth'
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | docker login \
            -u oauth2accesstoken \
            --password-stdin \
            https://${{ env.REGION }}-docker.pkg.dev 

      # 3. Build and Push the Image
      - name: Build and Push
        run: |
          IMAGE_URL="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL

      # 4. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          flags: '--allow-unauthenticated'